name: WolfGangRuleUI
main: WolfGangRule\Rules
version: 0.0.4
api: 3.0.0, 3.0.1, 3.2.1, 4.0.0
author: Wolfkid200444
description: Rule UI plugin Made by Wolfkid200444

commands:
    rules:
     usage: /rules
     description: ยง6Rules of the Server
