name: WolfGangRuleUI
main: WolfGangRule/Rules
version: 0.0.2
api: 3.0.0, 3.0.1, 3.0.2, 3.0.3
author: Wolfkid200444
description: Rule UI plugin Made by Wolfkid20044

  commands:
        rules:
         description: ยง6Rules of the Server