name: WolfGangRuleUI
main: WolfGangRule/Rules
version: 0.0.3
api: 3.0.0
author: Wolfkid200444
description: Rule UI plugin Made by Wolfkid20044

commands:
    rules:
      usage: /rules
          description: ยง6Rules of the Server
